#!/usr/bin/bash

POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
BASE_URL="https://pokeapi.co/api/v2/pokemon"
TYPE="application/json"
DIR="temp"
ERROR_FILE="$DIR/errors.txt"
FLAG=true


if [[ ! -d $DIR ]]; then
    mkdir $DIR
fi

handle_error() {
    echo "[$(date)]: $1" >> $ERROR_FILE
    exit 1
}

trap 'handle_error "An unexpected error occurred!"' ERR

handle_response() {
    if [[ $1 =~ ^2[0-9][0-9] ]]; then
        return 0
    else
        return 1
    fi
}

handle_fetch() {
    API_URL="$BASE_URL/$1"
    OUTPUT_FILE="$DIR/$1.json"

    RESPONSE=$(curl -X GET -s -w "%{http_code}" -o "$OUTPUT_FILE" -H "accept: $TYPE" "$API_URL")

    if ! handle_response "$RESPONSE"; then
        echo "Failed to fetch data of ($1) with HTTP Status Code $RESPONSE"
        rm -rf "$OUTPUT_FILE"
        FLAG=false
    fi
}

for POKEMON in "${POKEMONS[@]}";
do
    handle_fetch "$POKEMON"
    sleep 0.5
done

if $FLAG; then
    echo "Successfully fetched data"
fi