#!/usr/bin/bash

INPUT_FILE="data.json"

if [[ ! -f $INPUT_FILE ]]; then
  echo "Error: ($INPUT_FILE) not found"
  exit 1
fi

NAME=$(jq -r '.name' $INPUT_FILE | sed 's/^./\U&/')
TYPE=$(jq -r '.types[0].type.name' $INPUT_FILE | sed 's/^./\U&/')
HEIGHT=$(jq '.height' $INPUT_FILE | awk '{print $1/10}')
WEIGHT=$(jq '.weight' $INPUT_FILE | awk '{print $1/10}')

echo "$NAME is of type $TYPE, weighs ${WEIGHT}kg, and is ${HEIGHT}m tall."
# $name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall.