#!/usr/bin/bash

POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
DIR="temp"
CSV_FILE="pokemon_report.csv"

echo "Name,Height (m),Weight (kg)" > "$CSV_FILE"

for POKEMON in "${POKEMONS[@]}"
do
    FILE="$DIR/$POKEMON.json"

    if [[ ! -f $FILE ]]; then
        echo "ERROR: File $FILE not found."
        continue
    fi

    NAME=$(jq -r '.name' $FILE | sed 's/^./\U&/')
    HEIGHT=$(jq '.height' $FILE | awk '{print($1/10)}')
    WEIGHT=$(jq '.weight' $FILE | awk '{print($1/10)}')

    echo "$NAME,$HEIGHT,$WEIGHT" >> "$CSV_FILE"
done

echo "Report generated: $CSV_FILE"

awk -F ',' '
START {sumH=0; sumW=0; count=0; NR=1;}
    {sumH=sumH+$2; sumW=sumW+$3; count++}
END {print "AVG Height: " sumH/count "m\nAVG Weight: " sumW/count "Kg"}
' "$CSV_FILE"
